### ISSUE TITLE
Project groupId

### ISSUE THREAD

**Issue by jdmaturen** [hll/java-hll#6]
This project's groupId is [currently](https://github.com/hll/java-hll/blob/9718f193f84447043c0032c9cc60d3e97155d640/pom.xml#L5) `hll` which goes against Central's [recommendation (requirement?)](http://central.sonatype.org/pages/choosing-your-coordinates.html) of using reverse domain notation. We could use `io.github.hll` as we can publish to that http domain. We can just leave it and wait for Central to deny our application 😄. Thoughts @blinsay? /fyi @timonk @cscotta @d2fn

**Comment by blinsay** [comment]
My reading of that page is definitely a requirement, not a recommendation. Bah humbug. It looks like someone already owns `hll.io` so I'm down with `io.github.hll` (unless we want to buy something dumb like `hll.rocks`).

Should we also change the Java package name from `hll` to `io.github.hll`?

**Comment by jdmaturen** [comment]
> Should we also change the Java package name from `hll` to `io.github.hll`?

Sounds good to me. Though `hll.cool` is available, gimme a 👍 👎 on magical realism.

**Comment by jdmaturen** [comment]
🚢in it!
